spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/plinth}
    username: ${DATABASE_USERNAME:plinth}
    password: ${DATABASE_PASSWORD:plinth-local-dev}
    driver-class-name: org.postgresql.Driver
